source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
inhibit_all_warnings! 
use_frameworks!

target 'WineApp' do
  pod 'SwiftLint'
  pod 'naveridlogin-sdk-ios'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Pods for WineApp

end

inhibit_all_warnings! # cocoapods의 swiftlint 경고 메시지 해제
post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
